

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: garage-client
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "4000:3001"
    container_name: garage-server
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/garage
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: garage-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
